apiVersion: v1
kind: Service
metadata:
  name: maxkey
  namespace: maxkey
  labels:
    app: maxkey
spec:
  selector:
    app: maxkey
  ports:
    - name: http
      port: 9527
      targetPort: 9527
  type: ClusterIP
