apiVersion: v1
kind: Service
metadata:
  name: maxkey-mgt-frontend
  namespace: maxkey
  labels:
    app: maxkey-mgt-frontend
spec:
  selector:
    app: maxkey-mgt-frontend
  ports:
    - name: http
      port: 8526
      targetPort: 8526
  type: ClusterIP
