apiVersion: apps/v1
kind: Deployment
metadata:
  name: maxkey-frontend
  namespace: maxkey
  labels:
    app: maxkey-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maxkey-frontend
  template:
    metadata:
      labels:
        app: maxkey-frontend
    spec:
      containers:
        - name: maxkey-frontend
          image: maxkey-frontend
          ports:
            - containerPort: 8527
          readinessProbe:
            tcpSocket:
              port: 8527
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
